# -   repo: https://github.com/pre-commit/pre-commit-hooks
#     sha: v1.2.3
#     hooks:
#     -   id: debug-statements
#     -   id: flake8
# -   repo: https://github.com/ambv/black
#     rev: stable
#     hooks:
#     - id: black
#       language_version: python3.6


-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.1.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-docstring-first
    -   id: check-json
    -   id: check-yaml
    -   id: debug-statements
    -   id: name-tests-test
    -   id: requirements-txt-fixer
#     -   id: double-quote-string-fixer

-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.7.7
    hooks:
    -   id: flake8

-   repo: https://github.com/ambv/black
    rev: stable
    hooks:
    - id: black
      language_version: python3.6

-   repo: https://github.com/asottile/reorder_python_imports
    rev: v1.4.0
    hooks:
    -   id: reorder-python-imports
        language_version: python3

# -   repo: https://github.com/asottile/add-trailing-comma
#     rev: v1.0.0
#     hooks:
#     -   id: add-trailing-comma


# -   repo: local
#     hooks:
#     -   id: tests
#         name: run tests
#         entry: pytest -v
#         language: system
#         types: [python]
#         stages: [push]
