version: "3"
services:
  app:
    build: ./src
    depends_on:
      - db
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - DATABASE_URL=postgres://postgres:postgres@users-db:5432/users_dev
      - SECRET_KEY=my_precious
      - MY_PASS=HELLO

  db:
    image: mysql:5.7
    container_name: my-sql-conta
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
      - mysql:/var/lib/mysql

volumes:
  mysql:


    

    

    
